name: Github to AWS codecommit Sync
description: 'Synchronize from Github to codecommit via Github Actions using IAM credentials.'
author: 'Sougatd'
branding:
  icon: terminal
  color: yellow
inputs:
  repository_name: DevOps_Test_Repo
      ##description: CodeCommit repository name.
  required: true
aws_region: eu-west-3
  ##description: Region of the CodeComit Repository
  required: true
runs:
  using: 'docker'
  image: './Dockerfile'
  
